	export default function TermsOfService() {
	  return (
	    <div className="min-h-screen bg-gray-950 text-gray-300 py-16 px-4">
	      <div className="max-w-3xl mx-auto">
	        <h1 className="text-4xl font-bold text-white mb-8">Terms of Service</h1>
	        <p className="text-sm text-gray-500 mb-8">Last updated: {new Date().toLocaleDateString()}</p>
	        <div className="space-y-6 leading-relaxed">
	          <div>
	            <h2 className="text-2xl font-semibold text-white mb-3">1. Acceptance of Terms</h2>
	            <p>By accessing and using AI Workout to CSV, you accept and agree to be bound by the terms and provision of this agreement.</p>
	          </div>
	          <div className="bg-red-900/20 border border-red-800 p-6 rounded-lg">
	            <h2 className="text-2xl font-semibold text-red-400 mb-3">2. Medical Disclaimer (IMPORTANT)</h2>
	            <p className="font-semibold">The workout and diet plans generated by this website are provided by an Artificial Intelligence model and are for <strong>informational and educational purposes only</strong>.</p>
	            <p className="mt-3">This content does not constitute professional medical advice, diagnosis, or treatment. Always seek the advice of your physician or other qualified health provider with any questions you may have regarding a medical condition or before starting any new exercise program.</p>
	            <p className="mt-3"><strong>You assume all risk of injury or harm resulting from your use of the generated plans.</strong> Do not disregard professional medical advice or delay in seeking it because of something you have read on this website.</p>
	          </div>
	          <div>
	            <h2 className="text-2xl font-semibold text-white mb-3">3. Nature of AI-Generated Content</h2>
	            <p>The plans are generated by a machine learning model. While we optimize prompts for accuracy, we cannot guarantee that the exercises, sets, reps, or dietary macros will be safe or effective for every individual. Users must use their own judgment to determine what is appropriate for their fitness level.</p>
	          </div>
	          <div>
	            <h2 className="text-2xl font-semibold text-white mb-3">4. Limitation of Liability</h2>
	            <p>Under no circumstances shall the creators of AI Workout to CSV be liable for any direct, indirect, consequential, or incidental damages arising out of or in connection with your use of the website or the plans generated by it.</p>
	          </div>
	          <div>
	            <h2 className="text-2xl font-semibold text-white mb-3">5. Contact</h2>
	            <p>For any questions regarding these Terms, please contact us at <a href="mailto:support@aiworkingout.top" className="text-indigo-400 hover:underline">support@aiworkingout.top</a>.</p>
	          </div>
	        </div>
	      </div>
	    </div>
	  );
	}